module.exports = Object.freeze({
  NUMBER_OF_WINNERS: 3,
  BALLS_RANGE_START: 0,
  BALLS_RANGE_END: 49,
  FUND_PERCENTAGE: 0.5,
  FIRST_PRIZE_PERCENTAGE: 0.75,
  SECOND_PRIZE_PERCENTAGE: 0.15,
  THIRD_PRIZE_PERCENTAGE: 0.10,
  LIMIT_NUMBER_OF_PLAYERS: 50,
  TICKET_PRICE: 10,
  PURCHASE_COMMAND: 'purchase',
  DRAW_COMMAND: 'draw',
  WINNERS_COMMAND: 'winners',
  EXIT_COMMAND: 'exit'
});